# Generated by Django 4.1.1 on 2022-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
    ]
