# Generated by Django 4.1.1 on 2022-09-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='about',
            new_name='abo',
        ),
    ]
