# Generated by Django 4.1.1 on 2022-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_abo_registration_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='points',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
