# Generated by Django 4.1.1 on 2022-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_registration_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
