# Generated by Django 4.1.1 on 2022-09-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_score_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='points',
        ),
    ]
