# Generated by Django 4.1.1 on 2022-09-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_registration_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='point',
        ),
    ]
