# Generated by Django 4.1.1 on 2022-09-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_score_score_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='point',
            new_name='score',
        ),
    ]
