# Generated by Django 4.1.1 on 2022-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_point_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
