# Generated by Django 4.1.1 on 2022-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_registration_score_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(max_length=100),
        ),
    ]
